baseurl = "https://hilariofor25.com"
languageCode = "en-us"
title = "Hilario for 25"

[params]
  sizes = ["1600", "1200", "800", "600", "400"]
  tagline = "It's our time."

[menu]
  [[menu.main]]
    name = "Meet Hilario"
    url = "/meet-hilario/"
    weight = 1

  [[menu.main]]
    name = "Issues"
    url = "/issues/"
    weight = 10

  [[menu.main]]
    name = "Volunteer"
    url = "https://docs.google.com/forms/d/e/1FAIpQLSeb3va4ttqj2YEKoRes0-23etK68Qk9SR3v1zAxI76dWg1fKg/viewform"
    weight = 20
