backend:
  name: 'git-gateway'
  branch: 'netlify-cms'

media_folder: 'content/uploads'
public_folder: '/uploads'

collections:
  - name: 'issues'
    label: 'Issues'
    folder: 'content/issues'
    create: true
    fields:
      - {label: 'Title', name: 'title', widget: 'string'}
      - {label: 'Anchor Link', name: 'anchor', widget: 'string', pattern: ['[a-Z].*', 'Anchor link must start with a letter']}
      - {label: 'Image', name: 'image', widget: 'image'}
      - {label: 'Alt Text', name: 'alt', widget: 'string'}
      - {label: 'Weight', name: 'weight', widget: 'number', valuetype: 'int', hint: 'Weight determines the order of the issues on the page. A lower weight issue is placed higher on the page.'}
