---
label: Environmental Justice
hide_body: false
is_partial: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: anchor
  label: Anchor
  type: text
  hidden: false
  default: ''
- type: file
  label: Image
  name: image
