---
label: Environmental Justice
hide_body: 
is_partial: 
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: anchor
  label: Anchor
  type: text
  hidden: false
  default: ''
- name: image
  label: Image
  type: text
  hidden: false
  default: ''
